/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Pinak-PC' at '29/9/18 7:54 PM' with Gradle 2.14.1
 *
 * @author Pinak-PC, @date 29/9/18 7:54 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
